{
 "title": "Network Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Bytes Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "rawSql": "SELECT\n   v.time as time,\n  avg(v.bytes_per_second)*-1 as \"tx_avg\",\n  min(v.bytes_per_second)*-1 as \"tx_min\",\n  max(v.bytes_per_second)*-1 as \"tx_max\"\n\nFROM ( SELECT\n  $__timeGroup(d.time, $__interval),\n  avg(d.bytes_per_second) OVER(ORDER BY d.time ROWS BETWEEN 10 PRECEDING AND CURRENT ROW) as bytes_per_second\n\nFROM (SELECT\n  time,\n  (\n    CASE\n      WHEN bytes_sent >= lag(bytes_sent) OVER w\n        THEN bytes_sent - lag(bytes_sent) OVER w\n      WHEN lag(bytes_sent) OVER w IS NULL THEN NULL\n      ELSE bytes_sent\n    END\n  )  / extract(epoch from time - lag(time) OVER w) AS \"bytes_per_second\"\n  FROM traffic\n  WHERE $__timeFilter(time)\n  WINDOW w AS (ORDER BY time)\n  ORDER BY time\n) as d\n) as v\ngroup by time\norder by time"
    },
    {
     "rawSql": "SELECT\n   v.time as time,\n  avg(v.bytes_per_second) as \"rx_avg\",\n  min(v.bytes_per_second) as \"rx_min\",\n  max(v.bytes_per_second) as \"rx_max\"\n\nFROM ( SELECT\n  $__timeGroup(d.time, $__interval),\n  avg(d.bytes_per_second) OVER(ORDER BY d.time ROWS BETWEEN 10 PRECEDING AND CURRENT ROW) as bytes_per_second\n\nFROM (SELECT\n  time,\n  (\n    CASE\n      WHEN bytes_received >= lag(bytes_received) OVER w\n        THEN bytes_received - lag(bytes_received) OVER w\n      WHEN lag(bytes_received) OVER w IS NULL THEN NULL\n      ELSE bytes_sent\n    END\n  )  / extract(epoch from time - lag(time) OVER w) AS \"bytes_per_second\"\n  FROM traffic\n  WHERE $__timeFilter(time)\n  WINDOW w AS (ORDER BY time)\n  ORDER BY time\n) as d\n) as v\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "rawSql": "SELECT\n  time,\n  (\n    CASE\n      WHEN bytes_received >= lag(bytes_received) OVER w\n        THEN bytes_received - lag(bytes_received) OVER w\n      WHEN lag(bytes_received) OVER w IS NULL THEN NULL\n      ELSE bytes_received\n    END\n  ) / extract(epoch from time - lag(time) OVER w) AS \"bytes_per_second\"\nFROM traffic\nWHERE time > NOW() - INTERVAL '1 day'\nWINDOW w AS (ORDER BY time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT SUM(diffval) FROM (SELECT NON_NEGATIVE_DIFFERENCE(bytes_received) AS diffval FROM fritzbox WHERE $timeFilter FILL(previous))",
     "rawSql": "SELECT\n  time,\n  (\n    CASE\n      WHEN bytes_received >= lag(bytes_received) OVER w\n        THEN bytes_received - lag(bytes_received) OVER w\n      WHEN lag(bytes_received) OVER w IS NULL THEN NULL\n      ELSE bytes_received\n    END\n  ) AS \"bytes\"\n  FROM traffic\n  WHERE $__timeFilter(time)\n  WINDOW w AS (ORDER BY time)\n  ORDER BY time"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "rawSql": "SELECT\n  time,\n  (\n    CASE\n      WHEN bytes_sent >= lag(bytes_sent) OVER w\n        THEN bytes_sent - lag(bytes_sent) OVER w\n      WHEN lag(bytes_sent) OVER w IS NULL THEN NULL\n      ELSE bytes_sent\n    END\n  ) / extract(epoch from time - lag(time) OVER w) AS \"bytes_per_second\"\nFROM traffic\nWHERE time > NOW() - INTERVAL '1 day'\nWINDOW w AS (ORDER BY time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT SUM(diffval) FROM (SELECT NON_NEGATIVE_DIFFERENCE(bytes_sent) AS diffval FROM fritzbox WHERE $timeFilter FILL(previous))",
     "rawSql": "SELECT\n  time,\n  (\n    CASE\n      WHEN bytes_sent >= lag(bytes_sent) OVER w\n        THEN bytes_sent - lag(bytes_sent) OVER w\n      WHEN lag(bytes_sent) OVER w IS NULL THEN NULL\n      ELSE bytes_sent\n    END\n  ) AS \"bytes\"\n  FROM traffic\n  WHERE $__timeFilter(time)\n  WINDOW w AS (ORDER BY time)\n  ORDER BY time"
    }
   ]
  }
 ]
}