apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fritzbox-timescaledb-pusher
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"StatefulSet","name":"timescaledb"}]'
  labels:
    app.kubernetes.io/part-of: fritzbox-dashboard
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/drogue-iot/postgresql-pusher:0.1.0
          env:
            - name: RUST_LOG
              value: info
            - name: POSTGRESQL__TABLE
              value: traffic
            - name: POSTGRESQL__TIME_COLUMN
              value: time
            - name: POSTGRESQL__CONNECTION__HOST
              value: timescaledb
            - name: POSTGRESQL__CONNECTION__USER
              valueFrom:
                configMapKeyRef:
                  name: timescaledb-secret
                  key: adminUser
            - name: POSTGRESQL__CONNECTION__PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: timescaledb-secret
                  key: adminPassword
            - name: POSTGRESQL__CONNECTION__DBNAME
              valueFrom:
                configMapKeyRef:
                  name: timescaledb-config
                  key: databaseName
            - name: FIELD_BYTES_RECEIVED
              value: $.bytes_received
            - name: FIELD_BYTES_SENT
              value: $.bytes_sent
            - name: TAG_DEVICE_ID
              value: $.device_id
          resources:
            limits:
              memory: 64Mi
