{{- if .Values.kafka.topic.auth.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: drogue-iot-source-secret
data:
  mechanism: {{ .Values.kafka.topic.auth.mechanism | b64enc | quote }}
  user: {{ .Values.kafka.topic.auth.username | b64enc | quote }}
  password: {{ .Values.kafka.topic.auth.password | b64enc | quote }}
{{- end }}
