{{- if .Values.kafka.topic.auth.enabled }}
kind: Secrets
apiVersion: v1
metadata:
  name: drogue-iot-source-secret
data:
  mechanism: {{ .Values.kafka.topic.auth.mechanism | quote }}
  user: {{ .Values.kafka.topic.auth.username | quote }}
  password: {{ .Values.kafka.topic.auth.password | quote }}
{{- end }}
