{
 "title": "Network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Bytes Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Bytes Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT SUM(diffval) FROM (SELECT NON_NEGATIVE_DIFFERENCE(bytes_received) AS diffval FROM fritzbox WHERE $timeFilter FILL(previous))",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT SUM(diffval) FROM (SELECT NON_NEGATIVE_DIFFERENCE(bytes_sent) AS diffval FROM fritzbox WHERE $timeFilter FILL(previous))",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}