apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: fritzbox-dashboard-kafka-source
  labels:
    app.kubernetes.io/part-of: fritzbox-dashboard

spec:

  consumerGroup: fritzbox-dashboard

  bootstrapServers:
    - drogue-iot-kafka-bootstrap:9092

  topics:
    - events-ctron

  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: fritzbox-influxdb-pusher
