apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  labels:
    grafana: dashboards

configMapGenerator:
  - name: fritzbox-dashboards
    files:
      - dashboards/fritzbox.json

resources:
  - pusher-service.yaml
  - kafka-source.yaml
