apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: fritzbox-influxdb
  labels:
    app.kubernetes.io/name: fritzbox-influxdb
    app.kubernetes.io/part-of: fritzbox-dashboard
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: iot-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: fritzbox-influxdb-pusher
